CREATE TABLE `t_user`(
  `id` VARCHAR(100) PRIMARY KEY,
  `username` VARCHAR(20) NOT NULL UNIQUE,
  `password` VARCHAR(100) NOT NULL,
  `role_id` VARCHAR(100) NOT NULL,
  `locked` VARCHAR(100) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE `t_role`(
  `id` VARCHAR(100) PRIMARY KEY,
  `name` VARCHAR(20) NOT NULL UNIQUE,
  `description` VARCHAR(20) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;